//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRequestTools {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GB2312")]
        public string RequestEncoding {
            get {
                return ((string)(this["RequestEncoding"]));
            }
            set {
                this["RequestEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GB2312")]
        public string ResponseEncoding {
            get {
                return ((string)(this["ResponseEncoding"]));
            }
            set {
                this["ResponseEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23qYZaijQlmnkvwxyIN60GHOPopbcdRSWBCDKLM789AghEFTUVrstuefXJz145")]
        public string Login_tiancity_key_test {
            get {
                return ((string)(this["Login_tiancity_key_test"]));
            }
            set {
                this["Login_tiancity_key_test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60GHINOPopqRSWX45JKLM789ABCDEFYZabcdTUVrstuefghijQlmnkvwxyz123")]
        public string Login_tiancity_key {
            get {
                return ((string)(this["Login_tiancity_key"]));
            }
            set {
                this["Login_tiancity_key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tiancity")]
        public string Login_type {
            get {
                return ((string)(this["Login_type"]));
            }
            set {
                this["Login_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RequestEncoding_autoheader {
            get {
                return ((bool)(this["RequestEncoding_autoheader"]));
            }
            set {
                this["RequestEncoding_autoheader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://passport.tiancity.com/login/login_check_json.aspx?username={0}&cipherword" +
            "={1}&op=checkuser&checkcode={2}")]
        public string Login_tiancity_url {
            get {
                return ((string)(this["Login_tiancity_url"]));
            }
            set {
                this["Login_tiancity_url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int proxy_type {
            get {
                return ((int)(this["proxy_type"]));
            }
            set {
                this["proxy_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int output_len {
            get {
                return ((int)(this["output_len"]));
            }
            set {
                this["output_len"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string proxy_all {
            get {
                return ((string)(this["proxy_all"]));
            }
            set {
                this["proxy_all"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string proxy_use {
            get {
                return ((string)(this["proxy_use"]));
            }
            set {
                this["proxy_use"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool debug_msg {
            get {
                return ((bool)(this["debug_msg"]));
            }
            set {
                this["debug_msg"] = value;
            }
        }
    }
}
